# Generated by Django 3.0 on 2019-12-14 17:19
import json
import os

from django.db import migrations


def populate_models(apps, schema_editor):
    StateCapital = apps.get_model('state_capitals', 'StateCapital')

    dirname = os.path.dirname(__file__)
    filename = os.path.join(dirname, 'data/us_state_capitals.json')
    with open(filename) as file:
        capital_data = json.load(file)

    for abbr, data in capital_data.items():
        capital = StateCapital(**data)
        capital.save()


class Migration(migrations.Migration):

    dependencies = [
        ('state_capitals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_models)
    ]
